- name: Wait for RabbitMQ to start
  wait_for:
    port: 5672
    delay: 5
    timeout: 60

- name: Stop RabbitMQ app
  command: rabbitmqctl stop_app
  when: inventory_hostname != groups['rabbitmq'][0]

- name: Join cluster
  command: rabbitmqctl join_cluster {{ cluster_nodes[0] }}
  when: inventory_hostname != groups['rabbitmq'][0]

- name: Start RabbitMQ app
  command: rabbitmqctl start_app
  when: inventory_hostname != groups['rabbitmq'][0]

- name: Set ha-all policy
  command: >
    rabbitmqctl set_policy ha-all "^" '{"ha-mode":"all"}'
  when: inventory_hostname == groups['rabbitmq'][0]

